table: citas
primary_key: id_cita

read_csv:
  delimiter: ","
  header: 0

strip: true
lower: False

columns:

  - source: "Nº"
    name: numero_fila
    keep: false
    pandas_dtype: Int64
    sql_type: integer

  - source: "id_cita"
    name: id_cita
    keep: true
    pandas_dtype: Int64
    sql_type: serial

  - source: "id_lead"
    name: id_lead
    keep: true
    dropna: false
    pandas_dtype: Int64
    sql_type: bigint

  - source: "FECHA DE SOLICITUD "
    name: fecha_solicitud
    keep: true
    pandas_dtype: datetime64[ns]
    sql_type: timestamp

  - source: "FECHA DE CITA "
    name: fecha_cita
    keep: true
    pandas_dtype: datetime64[ns]
    sql_type: timestamp

  - source: "CLIENTE "
    name: cliente
    keep: true
    pandas_dtype: string
    sql_type: varchar(200)

  - source: "ASESOR "
    name: asesor
    keep: true
    pandas_dtype: string
    sql_type: varchar(150)

  - source: "GERENTE "
    name: gerente
    keep: true
    pandas_dtype: string
    sql_type: varchar(150)

  - source: "ASISTENCIA "
    name: asistencia
    keep: true
    pandas_dtype: string
    sql_type: varchar(30)
    transformations:
      - normalizar asistencia

  - source: "N. CITA "
    name: n_cita
    keep: true
    pandas_dtype: string
    sql_type: varchar(30)
    transformations:
      - mapear n citas

  - source: "PRODUCTO "
    name: producto
    keep: true
    pandas_dtype: string
    sql_type: varchar(150)

  - source: "TIPO DE CITA "
    name: tipo_cita
    keep: true
    pandas_dtype: string
    sql_type: varchar(100)

  - source: "CAPTACION"
    name: captacion
    keep: true
    pandas_dtype: string
    sql_type: varchar(100)

  - source: "CRM"
    name: registrado_crm
    keep: true
    pandas_dtype: boolean
    true_values: ["Registrado", "registrado", "Sí", "Si", "si", "sí"]
    sql_type: boolean

  - source: "VENTAS "
    name: ventas
    keep: true
    pandas_dtype: string
    sql_type: varchar(100)
    transformations: 
      - mapear ventas