table: stats_portales

primary_key:
  - periodo
  - id_portal

read_csv:
  delimiter: ","
  dtype: string
  
strip: true

columns:

  - source: "Período"
    name: periodo
    keep: true
    pandas_dtype: datetime64[ns]
    sql_type: timestamp

  - source: "Exposición"
    name: exposicion
    keep: true
    pandas_dtype: Int64
    sql_type: integer

  - source: "Visualizaciones"
    name: visualizaciones
    keep: true
    pandas_dtype: Int64
    sql_type: integer

  - source: "Consultas recibidas"
    name: consultas_recibidas
    keep: true
    pandas_dtype: Int64
    sql_type: integer

  - source: "Completaron el formulario"
    name: completaron_formulario
    keep: true
    pandas_dtype: Int64
    sql_type: integer

  - source: "Contactaron por Whatsapp"
    name: contactaron_por_whatsapp
    keep: true
    pandas_dtype: Int64
    sql_type: integer

  - source: "Vieron tus datos"
    name: vieron_tus_datos
    keep: true
    pandas_dtype: Int64
    sql_type: integer

  - source: "id_portal"
    name: id_portal
    keep: true
    pandas_dtype: Int64
    sql_type: integer